import type { AdminUser, ExtendedProduct, SubmittedDesign } from "./types"

export const initialUsers: AdminUser[] = [
  { id: "u_001", name: "Alice Johnson", email: "alice@example.com", role: "user", joinedAt: "2025-06-01" },
  { id: "u_002", name: "Bob Designer", email: "bob@example.com", role: "designer", joinedAt: "2025-05-21" },
  { id: "u_003", name: "Chris Lee", email: "chris@example.com", role: "user", joinedAt: "2025-05-10" },
  { id: "u_004", name: "Diana Cruz", email: "diana@example.com", role: "user", joinedAt: "2025-04-29" },
]

export const initialProducts: ExtendedProduct[] = [
  {
    id: "p_001",
    name: "Neon Hoodie",
    description: "Cyberpunk neon-lined hoodie with reflective seams.",
    price: 129,
    originalPrice: 159,
    categories: ["Apparel", "Hoodies"],
    category: "Apparel",
    subcategory: "Hoodies",
    tags: ["neon", "streetwear"],
    images: ["/neon-hoodie.png"],
    brand: "Meh",
    fabric: "Polyester",
    color: "Black",
    gender: "Unisex",
    fit: "Oversized",
    season: "Winter",
    style: "Streetwear",
    sizes: ["S", "M", "L", "XL"],
    status: "published",
    priority: "high",
    collection: "Cyberpunk Drop",
    inStock: true,
    isNew: true,
    isSale: true,
    createdAt: "2025-05-01",
    updatedAt: "2025-06-11",
  },
  {
    id: "p_002",
    name: "Glass Tee",
    description: "Ultra-soft tee with glassmorphism print.",
    price: 49,
    originalPrice: 59,
    categories: ["Apparel", "Tees"],
    category: "Apparel",
    subcategory: "Tees",
    tags: ["glassmorphism", "minimal"],
    images: ["/glass-tee.png"],
    brand: "Meh",
    fabric: "Cotton",
    color: "White",
    gender: "Unisex",
    fit: "Regular",
    season: "Summer",
    style: "Minimal",
    sizes: ["S", "M", "L"],
    status: "published",
    priority: "medium",
    collection: "Futurism Basics",
    inStock: true,
    isNew: true,
    isSale: false,
    createdAt: "2025-05-12",
    updatedAt: "2025-06-05",
  },
  {
    id: "p_003",
    name: "Retro Denim Jacket",
    description: "Classic denim jacket with distressed details.",
    price: 189,
    originalPrice: 189,
    categories: ["Apparel", "Jackets"],
    category: "Apparel",
    subcategory: "Jackets",
    tags: ["denim", "retro", "casual"],
    images: ["/retro-denim.png"],
    brand: "Meh",
    fabric: "Denim",
    color: "Blue",
    gender: "Unisex",
    fit: "Regular",
    season: "All Season",
    style: "Casual",
    sizes: ["M", "L", "XL"],
    status: "draft",
    priority: "low",
    collection: "Vintage Vibes",
    inStock: false,
    isNew: false,
    isSale: false,
    createdAt: "2025-04-15",
    updatedAt: "2025-05-02",
  },
]

export const initialDesigns: SubmittedDesign[] = [
  {
    id: "d_001",
    title: "Prismatic Grid",
    imageUrl: "/prismatic-grid.png",
    author: "Alice Johnson",
    submittedAt: "2025-06-15T14:21:00Z",
    branded: false,
    status: "pending",
  },
  {
    id: "d_002",
    title: "Neon Flux",
    imageUrl: "/neon-flux-poster.png",
    author: "Chris Lee",
    submittedAt: "2025-06-16T09:05:00Z",
    branded: true,
    status: "pending",
  },
]
